### ISSUE TITLE
Checks fail if packages get is executed before rename project script

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#99]
Error:
```
Starting the final content reference check...
./.packages content still contains some template references
./.dart_tool/package_config.json content still contains some template references
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = './.fvm/flutter_sdk/bin/cache/artifacts/libimobiledevice/idevicesyslog'
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      _performFinalCheck.<anonymous closure> (file:///Users/hannesvandenberghe/Developer/my_app/tool/dart_tool/rename_project.dart:307:40)
#3      Iterable.forEach (dart:core/iterable.dart:283:30)
#4      _performFinalCheck (file:///Users/hannesvandenberghe/Developer/my_app/tool/dart_tool/rename_project.dart:303:6)
#5      main (file:///Users/hannesvandenberghe/Developer/my_app/tool/dart_tool/rename_project.dart:63:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Comment by vanlooverenkoen** [comment]
Got a similar issue
```
FileSystemException: Failed to decode data using encoding 'utf-8', path = './.DS_Store'
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      _performFinalCheck.<anonymous closure> (file:///Users/vanlooverenkoen/Documents/projects/app_center_client/tool/dart_tool/rename_project.dart:307:40)
#3      Iterable.forEach (dart:core/iterable.dart:283:30)
#4      _performFinalCheck (file:///Users/vanlooverenkoen/Documents/projects/app_center_client/tool/dart_tool/rename_project.dart:303:6)
#5      main (file:///Users/vanlooverenkoen/Documents/projects/app_center_client/tool/dart_tool/rename_project.dart:63:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```
